---
#TODO: check if required when MS user is 'root'
- name: edit IBM IoT MessageSight service settings
  systemd: 
    name: "{{ item }}.service"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items: "{{ common.iotms.rpm_files }}"

#refactor: insertafter: 'regex' does not work yet - block is inserted at wrong point
- name: add IBM IoT MessageSight user and group for service 
  blockinfile:
    block: |
      User={{ common.iotms.user }}
      Group:{{ common.iotms.group}}
    path: "/etc/systemd/system/{{ item }}.service"
    insertafter: "[Service]"
  with_items: "{{ common.iotms.rpm_files }}"
    
