---

- name: set user limits
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  with_items: "{{ common.iotms.settings.user_limits }}"
  become: yes

...