---
- name: create passive multi-instance queue manager {{ host.mqvars.passive_qmgr.name }}
  command: >
    "{{ common.mq.directories.onhosts.mq_binaries }}addmqinf 
    -v Name={{ common.mq.qmgrs.passive_qmgr }} 
    -v Directory={{ common.mq.qmgrs.passive_qmgr }} 
    -v Prefix={{ common.mq.directories.onhosts.qmgrs_dir }} 
    -v DataPath={{ common.mq.directories.onhosts.qmgrs_dir }}"
  when: host.mqvars.is_multi_instance