---
- name: "create passive multi-instance queue manager {{ item.value.name }}"
  command: >
    {{ common.mq.directories.onhosts.required.mq_binaries }}addmqinf
    -v Name={{ item.value.name }}
    -v Directory={{ item.value.name }}
    -v Prefix={{ common.mq.directories.onhosts.required.mq_data }}
    -v DataPath={{ common.mq.directories.onhosts.required.qmgrs_dir }}/{{ item.value.name }}
  with_dict: "{{ host.mqvars.qmgrs }}"
  when: >
    (item.value.is_multi_instance)
    and not (item.value.is_primary_instance)