---
- name: create server connection channel
  command: > 
        "echo \"DEFINE CHL({{ host.mqvars.active_qmgr.srvconnchannel01.name }})
        CHLTYPE(SVRCONN)
        TRPTYPE(TCP)
        DESCR('{{ host.mqvars.active_qmgr.srvconnchannel01.description}}')
        REPLACE\"
        | {{ common.mq.directories.onhosts.mq_binaries }}runmqsc {{ host.mqvars.active_qmgr.name }}"