---
- name: create secondary multi-instance queue manager {{ common.mq.qmgrs.secondary_qmgr }}
  command: >
    "{{ common.mq.directories.onhosts.mq_binaries }}crtmqm 
    -md {{ common.mq.directories.onhosts.qmgrs_dir }} 
    -ld {{ common.mq.directories.onhosts.log_dir }} 
    {{ common.mq.qmgrs.secondary_qmgr }}"
  
- name: add primary multi-instance queue manager {{ common.mq.qmgrs.primary_qmgr }}
  command: >
    "{{ common.mq.directories.onhosts.mq_binaries }}addmqinf 
    -v Name={{ common.mq.qmgrs.primary_qmgr }} 
    -v Directory={{ common.mq.qmgrs.primary_qmgr }} 
    -v Prefix={{ common.mq.directories.onhosts.qmgrs_dir }} 
    -v DataPath={{ common.mq.directories.onhosts.qmgrs_dir }}"
  
- name: start secondary queue manager {{ common.mq.qmgrs.secondary_qmgr }} in multi-instance mode
  command: "{{ common.mq.directories.onhosts.mq_binaries }}strmqm -x {{ common.mq.qmgrs.secondary_qmgr }}"
  
#TODO: rename? add fail module or remove (not really necessary task)?
- name: Observe the secondary queue manager {{ common.mq.qmgrs.secondary_qmgr }} running in active mode
  command: {{ common.mq.directories.onhosts.mq_binaries }}dspmq -x
  
#TODO: following three: necessary tasks? -> should rather go in a role for verification of HA scenario
- name: Start primary queue manager {{ common.mq.qmgrs.primary_qmgr }}. Observe the queue manager running in standby mode
  command: "{{ common.mq.directories.onhosts.mq_binaries }}strmqm -x {{ common.mq.qmgrs.primary_qmgr }}"
  
- name: Test HA scenario by stopping {{ common.mq.qmgrs.secondary_qmgr }}
  command: "{{ common.mq.directories.onhosts.mq_binaries }}endmqm -s {{ common.mq.qmgrs.secondary_qmgr }}"
  
- name: restart queue manager {{ common.mq.qmgrs.secondary_qmgr }}
  command: "{{ common.mq.directories.onhosts.mq_binaries }}strmqm -x {{ common.mq.qmgrs.secondary_qmgr }}"