---
#TODO: check if localhost is working
- name: set in-memory hosts (group 1)
  hosts: localhost
  add_host:
    name: "{{ item.1 }}"
    groups: MQ01
  with_indexed_items: "{{ ansible_play_hosts }}"
  when: "item.0 < (ansible_play_hosts | length//2)"

- name: create multi-instance queue manager {{ queuedata.qmgr1 }} on host A
  hosts: MQ01
  command: "crtmqm -md {{ webspheremq_qmgrs_directory }} -ld {{ webspheremq_log_directory }} {{ queuedata.qmgr1 }}"
  
  #TODO: obsolute as we have all the data already?
#- name: prepare creation1 of multi-instance queue manager {{ queuedata.qmgr1 }} on host B
  #hosts: MQ02
  #command: "dspmqinf -o command {{ queuedata.qmgr1 }}"
  #or: "command: dspmqinf QM01" for getting output in multiple lines
  #TODO: use string separation and loop for storing values in different variables?
  
- name: create multi-instance queue manager {{ queuedata.qmgr1 }} on host B
  hosts: MQ02
  command: "addmqinf -v Name={{ queuedata.qmgr1 }} -v Directory={{ queuedata.qmgr1 }} -v Prefix={{ webspheremq_qmgrs_directory }} -v DataPath={{ webspheremq_qmgrs_directory }}"
  
- name: start queue manager {{ queuedata.qmgr1 }} in multi-instance mode on host A
  hosts: MQ01
  command: "strmqm -x {{ queuedata.qmgr1 }}"
  
#TODO: rename?
- name: Observe the queue manager {{ queuedata.qmgr1 }} running in active mode on host A
  hosts: MQ01
  command: dspmq -x
  
#TODO: any command here?
- name: Start queue manager {{ queuedata.qmgr1 }} on host B. Observe the queue manager running in standby mode
  hosts: MQ02
  command: "strmqm -x {{ queuedata.qmgr1 }}"
  
- name: Test HA scenario by stopping {{ queuedata.qmgr1 }} on host A
  hosts: MQ01
  command: "endmqm -s {{ queuedata.qmgr1 }}"
  
- name: restart queue manager {{ queuedata.qmgr1 }} on host A
  hosts: MQ01
  command: "strmqm -x {{ queuedata.qmgr1 }}"