#main MQ multi instance configuration yml

#TODO: other possible version: include generic task for creating QM, in which is decided to create single-instance, multi-instance-prim. or -sec.
#then also do this with adding and with starting mq
- name: create active queue managers 
  import_tasks: create_active.yml
  become_user: "{{ common.mq.user }}"
  become: yes
  tags: configuremq

- name: add passive queue managers 
  import_tasks: add_passive.yml
  become_user: "{{ common.mq.user }}"
  become: yes
  tags: configuremq
  
- name: start active queue managers 
  import_tasks: start_active.yml
  become_user: "{{ common.mq.user }}"
  become: yes
  tags: configuremq