# Role MQ

- name: role for configuring MQ
  hosts: all
  vars_files: 
    - inventories/common/vars.yml
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ common.mq.directories.onhosts.required.installation_dir }}bin"
  become_user: "{{ common.mq.user }}"
  become: yes
  roles:
    - mqconfigbase
