---
- name: Ensure Filesystem directories are available
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ common.mq.user }}"
    group: "{{ common.mq.group }}"
  with_dict: "{{ common.mq.directories.onhosts }}"
  become: true
...