---
- name: Ensure Filesystem directories are available
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ webspheremq.user }}"
    group: "{{ webspheremq.group }}"
  with_items: "{{ webspheremq_internal.required_directories }}"
  become: true
...