---
- name: Ensure Filesystem directories are available
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mq.user }}"
    group: "{{ mq.group }}"
  with_dict: "{{ mq.directories }}"
  become: true
...