---
#file and process settings - max number of processes for user mqm and max 
#number of file descriptors for running process

- name: set file and process settings
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  with_items: "{{ webspheremq_internal.user_limits }}"
  become: true

...