---    
# set recommended minimum Linux kernel parameters
#TODO: implement loop (see http://docs.ansible.com/ansible/latest/playbooks_loops.html#id4)

- name: Enable without reboot
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
  with_items: "{{ common.mq.settings.sysctl_settings }}"
  become: yes    
...