---
#unpack binaries

- name: Ensure Install package is available
  stat:
    path: "{{ mq.directories.installation_archive_path }}"

- name: unpack MQ installation binaries
  unarchive: src="{{ mq.directories.installation_archive_path }}" dest="{{ mq.directories.unarchive_dir }}" 
  become: yes
  
- name: cleanup MQ installation binaries archive
  file:
    path: "{{ mq.directories.archive_dir }}"
    state: absent
  become: true
  
...