---
#Verify correct WebSphere MQ installation

- name: verification of MQ installation
  import_tasks: verify_all.yml
  become_user: "{{ common.mq.user }}"
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ common.mq.directories.onhosts.required.installation_dir }}bin"
   
...