---
# Development environment
#TODO: remove sample data "foo"

host:
  mqvars:
    is_multi_instance: true
    is_primary_instance: false
    active_qmgr: 
      name: QM02
      listener01: 
        name: listener01
        port: 1414
        description: standard listener
      queues:
        mqtt_local:
          name: mqtt_local01
          description: local MQTT queue
        mqtt01: 
          name: mqtt_queue01
          description: MQTT queue
      channels:
        srv_conn01:
          name: srvconnchannel01
          description: MQ server connection channel
        mqtt01:
          name: mqttchannel01
          port: 1883
          description: MQTT channel
      topics:
        topic01:
          name: foo
          topicstr: /foo/bar
      subscriptions:
        sub01:
          name: foo
    passive_qmgr: 
      name: QM01
