---
#- name: stop all processes of MQ user
#  import_tasks: stopprocesses.yml
#  tags: uninstallmq
  
- name: uninstall MQ packages
  import_tasks: uninstallpackages.yml
  
- name: remove MQ rpm packages
  import_tasks: removepackages.yml

- name: remove binaries
  import_tasks: removebinaries.yml

- name: remove MQ data folder {{ common.mq.directories.onhosts.required.mq_home }}
  import_tasks: deletefolders.yml
 
- name: remove user {{ common.mq.user }}
  import_tasks: removeuser.yml
  
- name: remove group {{ common.mq.group }}
  import_tasks: removegroup.yml
