#TODO: does NOT correctly remove installed packages -> files are deleted, but packages are still registered as installed in yum
- name: Uninstall packages
  yum:
    name: "{{ item }}"
    state: absent
    update_cache: yes
  with_items: "{{ mq.rpm_files }}"
  become: true