# Deletes all MQ packages if any installed
  
- name: Uninstall packages using the shell
  shell: "if [[ $(rpm -qa | grep MQSeries) ]]; then rpm -qa | grep MQSeries | xargs rpm -ev; fi"
  become: yes
