---
# This playbook create a technical user for IIB

- name: create IIB user
  user:
    name: "{{ common.iib.user }}"
    uid: "{{ common.iib.uid }}"
    shell: /bin/bash
    group: "{{ common.iib.group }}"
    groups: "{{ common.mq.group }}"
    append: yes
  become: yes
