---
# This playbook installs the IIB binaries.

- name: unpack IIB installation binaries.
  become: yes
  unarchive:
    src: "{{ common.iib.installation_dir }}/iib-{{ common.iib.version }}.tar.gz"
    dest: "{{ common.iib.installation_dir }}"
    remote_src: yes

- name: cleanup IIB installation binaries archive.
  become: yes
  file: 
    path: "{{ common.iib.installation_dir }}/iib-{{ common.iib.version }}.tar.gz"
    state: absent

- name: install IIB
  become: yes
  shell: | 
    cd "{{ common.iib.binaries_dir }}"
    ./iib make registry global accept license silently

- name: set ownership of installed IIB binaries to IIB user and group.
  become: yes
  file: 
    path: "{{ common.iib.binaries_dir }}"
    state: directory
    recurse: yes
    owner: "{{ common.iib.user }}"
    group: "{{ common.iib.group }}"

- name: set ownership of IIB data directory to IIB user and group.
  become: yes
  file:
    path: "{{ common.iib.data_dir }}"
    state: directory
    recurse: yes
    owner: "{{ common.iib.user }}"
    group: "{{ common.iib.group }}"
