---
# This playbook create a technical user for IIB

- name: remove IIB user
  user:
    name: "{{ iib.user }}"
    state: absent # deletes user
    remove: yes # deletes users home dir
  become: true
