---
# This playbook unpacks the IIB installation package.

- name: unpack IIB installation package.
  become: yes
  unarchive:
    src: "{{ common.iib.installation_package_path }}"
    dest: "{{ common.iib.installation_package_unarchive_dir }}"

- name: copy IIB binaries archive to installation location.
  become: yes
  copy:
    src: "{{ common.iib.installation_package_unarchive_dir }}/EAsmbl_image/iib-{{ common.iib.version }}.tar.gz"
    dest: "{{ common.iib.installation_dir }}/iib-{{ common.iib.version }}.tar.gz"
    remote_src: yes

- name: cleanup unpacked IIB installation package.
  become: yes
  file: 
    path: "{{ common.iib.installation_package_unarchive_dir }}/{{ common.iib.installation_package_unarchive_name }}"
    state: absent
