---
#Verify correct WebSphere MQ installation

- name: verification of MQ installation
  import_tasks: verify_all.yml
  become_user: "{{  webspheremq.user }}"
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/mqm/bin"  
...